<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Testing003-PC" name="com.testScripts.Bill_Settlement_Test" tests="55" failures="7" timestamp="29 Apr 2017 10:43:31 GMT" time="829.300" errors="0">
  <testcase name="BS_52_Verify_Name_on_CreditCard_With_InValid_Alphanumeric" time="27.464" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_70_Verify_BankName_with_SplChar_Invalid" time="35.398" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_77_Verify_Cheque_Number_with_Blank_Invalid" time="0.005" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_73_Verify_BankName_with_Maximum_15_Char_Valid" time="33.396" classname="com.testScripts.Bill_Settlement_Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.pageLibrary.Bill_Settlement.bs_73_Verify_BankName_with_Maximum_15_Char_Valid(Bill_Settlement.java:2289)
	at com.testScripts.Bill_Settlement_Test.BS_73_Verify_BankName_with_Maximum_15_Char_Valid(Bill_Settlement_Test.java:233)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- BS_73_Verify_BankName_with_Maximum_15_Char_Valid -->
  <testcase name="BS_59_Verify_Credit_Card_Number_with_Blank_Invalid" time="26.310" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_66_Verify_Amount_Lessthan_or_Equal_to_NetAmount" time="43.481" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_228_Verify_Credit_Card_Number_with_Alphabets_Invalid" time="26.429" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_104_Verify_Cheque_Date_Blank_Invalid" time="0.002" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_100_Verify_Cheque_Date_with_Morethan_SystemDate" time="0.002" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_69_Verify_BankName_with_Alphabets_Valid" time="34.284" classname="com.testScripts.Bill_Settlement_Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.pageLibrary.Bill_Settlement.bs_69_Verify_BankName_with_Alphabets_Valid(Bill_Settlement.java:1818)
	at com.testScripts.Bill_Settlement_Test.BS_69_Verify_BankName_with_Alphabets_Valid(Bill_Settlement_Test.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- BS_69_Verify_BankName_with_Alphabets_Valid -->
  <testcase name="BS_81_Verify_Cheque_Payee_with_Alphabets_Valid" time="0.004" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_82_Verify_Cheque_Payee_with_Spl_Char_Invalid" time="0.003" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_63_Verify_Default_Option_At_Credit_Card_Type_Dropdown" time="20.669" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_62_Verify_Credit_Card_Number_with_below_4_digits_Invalid" time="27.546" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_58_Verify_Credit_Card_Number_with_SpecialChar_Invalid" time="27.486" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_229_Verify_BankName_with_Numeric_Invalid" time="33.364" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_225_Verify_Name_on_CreditCard_With_InValid_Numeric" time="14.766" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_224_Verify_Name_on_CreditCard_With_InValid_SpecialCharacters" time="27.476" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_86_Verify_Cheque_Payee_with_Morethan_20_Char_Invalid" time="0.004" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_226_Verify_Name_on_CreditCard_with_below_6_Characters_Invalid" time="27.456" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_67_Verify_Amount_with_Morethan_NetAmount" time="30.332" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_230_Verify_BankName_with_AlphaNumeric_Invalid" time="33.383" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_83_Verify_Cheque_Payee_with_Minimum_3_Char_Valid" time="0.005" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_87_Verify_Cheque_Payee_with_Blank_Invalid" time="0.002" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_99_Verify_Cheque_Date_format" time="0.002" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_76_Verify_Cheque_Number_with_Spl_Char_Invalid" time="0.005" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_72_Verify_BankName_with_Minimum_3_Char_Valid" time="33.436" classname="com.testScripts.Bill_Settlement_Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.pageLibrary.Bill_Settlement.bs_72_Verify_BankName_with_Minimum_3_Char_Valid(Bill_Settlement.java:2219)
	at com.testScripts.Bill_Settlement_Test.BS_72_Verify_BankName_with_Minimum_3_Char_Valid(Bill_Settlement_Test.java:226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- BS_72_Verify_BankName_with_Minimum_3_Char_Valid -->
  <testcase name="BS_231_Verify_Cheque_Number_with_Alphabets_Invalid" time="0.005" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_68_Verify_PaymentMode_Cheque_Option" time="10.692" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_234_Verify_Cheque_Payee_with_AlphaNumeric_Invalid" time="0.003" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_85_Verify_Cheque_Payee_with_Maximum_20_Char_Valid" time="0.001" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_233_Verify_BankName_with_below_3_Char_Invalid" time="0.003" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_61_Verify_Credit_Card_Number_with_Morethan_4_digits_Invalid" time="25.249" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_74_Verify_BankName_with_Morethan_15_Char_Invalid" time="33.465" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_78_Verify_Cheque_Number_with_Minimum_6_Digits_Valid" time="0.011" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_71_Verify_BankName_with_Blank_Invalid" time="32.182" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_101_Verify_Cheque_Date_with_Lessthan_SystemDate" time="0.002" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_55_Verify_Name_on_Credit_Card_Textbox_with_Maximum_30_Char_Valid" time="15.442" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_53_Verify_Name_on_CreditCard_Without_Entering_Name" time="13.209" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_75_Verify_Cheque_Number_with_Numeric_Valid" time="0.011" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_51_Verify_Name_on_CreditCard_With_Valid_Alphabets" time="28.452" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_102_Verify_Amount_Lessthan_or_Equal_to_NetAmount" time="0.004" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_103_Verify_Amount_Morethan_NetAmount_Invalid" time="0.006" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_57_Verify_CreditCard_Number_with_Numeric_Valid" time="27.505" classname="com.testScripts.Bill_Settlement_Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.pageLibrary.Bill_Settlement.bs_57_Verify_CreditCard_Number_with_Numeric_Valid(Bill_Settlement.java:838)
	at com.testScripts.Bill_Settlement_Test.BS_57_Verify_CreditCard_Number_with_Numeric_Valid(Bill_Settlement_Test.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- BS_57_Verify_CreditCard_Number_with_Numeric_Valid -->
  <testcase name="BS_65_Verify_Credit_Card_Type_with_Blank_Invalid" time="25.281" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_227_Verify_Credit_Card_Number_with_Alphanumeric_Invalid" time="27.516" classname="com.testScripts.Bill_Settlement_Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.pageLibrary.Bill_Settlement.bs_227_Verify_Credit_Card_Number_with_Alphanumeric_Invalid(Bill_Settlement.java:953)
	at com.testScripts.Bill_Settlement_Test.BS_227_Verify_Credit_Card_Number_with_Alphanumeric_Invalid(Bill_Settlement_Test.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- BS_227_Verify_Credit_Card_Number_with_Alphanumeric_Invalid -->
  <testcase name="BS_235_Verify_Cheque_Payee_with_Numeric_Invalid" time="0.003" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_64_Verify_Credit_Card_Type_Dropdown_Valid" time="20.774" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_60_Verify_CreditCard_Number_with_4_Digits_Valid" time="27.369" classname="com.testScripts.Bill_Settlement_Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.pageLibrary.Bill_Settlement.bs_60_Verify_CreditCard_Number_with_4_Digits_Valid(Bill_Settlement.java:1119)
	at com.testScripts.Bill_Settlement_Test.BS_60_Verify_CreditCard_Number_with_4_Digits_Valid(Bill_Settlement_Test.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- BS_60_Verify_CreditCard_Number_with_4_Digits_Valid -->
  <testcase name="BS_232_Verify_Cheque_Number_with_AlphaNumeric_Invalid" time="0.021" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_84_Verify_Cheque_Payee_with_Lessthan_3_Char_Invalid" time="0.006" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_80_Verify_Cheque_Number_with_Morethan_6_Digits_Invalid" time="0.005" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_56_Verify_Name_on_CreditCard_with_Morethan_30_Char_Invalid" time="27.558" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_79_Verify_Cheque_Number_with_Lessthan_6_Digits_Invalid" time="0.005" classname="com.testScripts.Bill_Settlement_Test"/>
  <testcase name="BS_54_Verify_Name_on_Credit_Card_Textbox_with_Minimum_6_Char_Valid" time="11.810" classname="com.testScripts.Bill_Settlement_Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.pageLibrary.Staff_Login.sl_11_Verify_Staff_Login_Valid_Username_Valid_Password(Staff_Login.java:413)
	at com.pageLibrary.Bill_Settlement.bs_54_Verify_Name_on_Credit_Card_Textbox_with_Minimum_6_Char_Valid(Bill_Settlement.java:578)
	at com.testScripts.Bill_Settlement_Test.BS_54_Verify_Name_on_Credit_Card_Textbox_with_Minimum_6_Char_Valid(Bill_Settlement_Test.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- BS_54_Verify_Name_on_Credit_Card_Textbox_with_Minimum_6_Char_Valid -->
</testsuite> <!-- com.testScripts.Bill_Settlement_Test -->
